export const GET_ALL_CONTACT_SUCCESS = 'GET_ALL_CONTACT_SUCCESS';
export const GET_ALL_CONTACT_ERROR = 'GET_ALL_CONTACT_ERROR';

export const SET_CONTACT_SUCCESS = 'SET_CONTACT_SUCCESS';
export const SET_CREATE_LOADING = 'SET_CREATE_LOADING';
export const SET_LOADING = 'SET_LOADING';

export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';

export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_ERROR = 'UPDATE_CONTACT_ERROR';
